model_list:
  # OpenAI Models
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      timeout: 300
      max_retries: 3

  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
      timeout: 120
      max_retries: 3

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
      timeout: 120
      max_retries: 3

  # Anthropic Models
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
      timeout: 300
      max_retries: 3

  - model_name: claude-3-5-haiku
    litellm_params:
      model: claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
      timeout: 120
      max_retries: 3

  - model_name: claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
      timeout: 300
      max_retries: 3

# Router Settings
router_settings:
  routing_strategy: usage-based-routing-v2
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD
  enable_pre_call_checks: true

# General Settings
litellm_settings:
  drop_params: true
  set_verbose: false
  json_logs: true
  
  # Caching
  cache: true
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
    password: os.environ/REDIS_PASSWORD
    ttl: 3600
  
  # Rate Limiting
  num_retries: 3
  request_timeout: 300

  # Content Moderation (disabled - configure separately if needed)
  enable_content_moderation: false

  # Fallbacks (simple list of model names)
  fallbacks:
    - gpt-4o-mini
    - claude-3-5-haiku

# Success/Failure Callbacks (add monitoring services to enable)
# success_callback: ["langfuse", "prometheus"]
# failure_callback: ["langfuse", "prometheus"]

# General Settings for all models
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL

  # Budgets and Rate Limits
  max_budget: 100.0
  budget_duration: "1d"

  # Logging
  store_model_in_db: true

  # UI Settings
  ui_access_mode: "admin_only"

# Environment Variables
environment_variables:
  OPENAI_API_KEY:
    type: secret
  ANTHROPIC_API_KEY:
    type: secret
  REDIS_HOST:
    type: string
  REDIS_PORT:
    type: integer
  REDIS_PASSWORD:
    type: secret
  DATABASE_URL:
    type: secret
  LITELLM_MASTER_KEY:
    type: secret
