global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

ping:
  entryPoint: "web"

entryPoints:
  web:
    address: ":80"
    http:
      middlewares:
        - security-headers@file

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
  file:
    directory: /dynamic
    watch: true

log:
  level: DEBUG
  format: json
  filePath: /var/log/traefik/traefik.log

accessLog:
  format: json
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "200-599"  # Log all responses for debugging
    retryAttempts: true
    minDuration: "1ms"  # Lower threshold for debugging

# Rate limiting
http:
  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m
